export const SKILLS = [
    {
        title: "Frontend",
        icon: "./assets/images/icons/frontend/frontend.webp",
        skills: [
            { skill: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp" },
            { skill: "CSS", iconUrl: "./assets/images/icons/frontend/css3.webp" },
            { skill: "SASS", iconUrl: "./assets/images/icons/frontend/sass.webp" },
            { skill: "Bootstrap", iconUrl: "./assets/images/icons/frontend/bootstrap.webp" },
            { skill: "JavaScript", iconUrl: "./assets/images/icons/frontend/javascript.webp" },
            { skill: "React", iconUrl: "./assets/images/icons/frontend/react.webp" },
            { skill: "jQuery", iconUrl: "./assets/images/icons/frontend/jquery.webp" },
            { skill: "Responsive Design", iconUrl: "./assets/images/icons/frontend/responsive.webp" },
        ],
    },
    {
        title: "Backend",
        icon: "./assets/images/icons/backend/backend.webp",
        skills: [
            { skill: "PHP", iconUrl: "./assets/images/icons/backend/php.webp" },
            { skill: "MariaDB", iconUrl: "./assets/images/icons/backend/mariadb.webp" },
            { skill: "Node JS", iconUrl: "./assets/images/icons/backend/nodejs.webp" },
        ],
    },
    {
        title: "Tools",
        icon: "./assets/images/icons/tools/tools.webp",
        skills: [
            { skill: "Git", iconUrl: "./assets/images/icons/tools/git.webp" },
            { skill: "GitHub", iconUrl: "./assets/images/icons/tools/github.webp" },
            { skill: "NPM", iconUrl: "./assets/images/icons/tools/npm.webp" },
            { skill: "WordPress", iconUrl: "./assets/images/icons/tools/wordpress.webp" },
            { skill: "Visual Studio Code", iconUrl: "./assets/images/icons/tools/vscode.webp" },
            { skill: "Google Workspace", iconUrl: "./assets/images/icons/tools/workspace.webp" },
            { skill: "Figma", iconUrl: "./assets/images/icons/tools/figma.webp" },
            { skill: "Office", iconUrl: "./assets/images/icons/tools/office.webp" },

        ],
    },
    {
        title: "Soft Skills",
        icon: "./assets/images/icons/soft-skills/soft-skills.webp",
        skills: [
            { skill: "Problem-solving", iconUrl: "./assets/images/icons/soft-skills/problem-solving.webp" },
            { skill: "Attention to Detail", iconUrl: "./assets/images/icons/soft-skills/attention.webp" },
            { skill: "Organisation", iconUrl: "./assets/images/icons/soft-skills/organisation.webp" },
            { skill: "Communication", iconUrl: "./assets/images/icons/soft-skills/communication.webp" },
        ],
    },
]

export const PROJECTS = [
    {
        title: "Ziggy PrintIT eCommerce Site",
        role: "Sole Developer",
        technologies: [
            {name: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp"},
            {name: "SASS", iconUrl: "./assets/images/icons/frontend/sass.webp"},
            {name: "JavaScript", iconUrl: "./assets/images/icons/frontend/javascript.webp"},
            {name: "WordPress", iconUrl: "./assets/images/icons/tools/wordpress.webp"},
            {name: "PHP", iconUrl: "./assets/images/icons/backend/php.webp"},
            {name: "ACF", iconUrl: "./assets/images/icons/tools/acf.webp"},
        ],
        description: "An eCommerce website for selling print on demand products.\n \nThis site uses WordPress' Woocommerce platform, that is integrated with Printful to import the products once they are created on the Printful Platform. \n \nThis is the first eCommerce website I have created and enjoyed every moment of it. I enjoyed using new tools that I haven't before..",
        screenshot: "./assets/images/screenshots/ziggy-printit-screenshot.webp",
        repo: "",
        repoTitle: "",
        deployed: "https://ziggyprintit.co.uk",
        deployedTitle: "Ziggy PrintIT",
    },
    {
        title: "Raindrops on Roses Florist",
        role: "Sole Developer",
        technologies: [
            {name: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp"},
            {name: "SASS", iconUrl: "./assets/images/icons/frontend/sass.webp"},
            {name: "WordPress", iconUrl: "./assets/images/icons/tools/wordpress.webp"},
            {name: "PHP", iconUrl: "./assets/images/icons/backend/php.webp"},
            
        ],
        description: "A family member runs a local floristry business, so I worked with her to create this website.\n \nThe website was required to showcase her work, as she did not want an eCommerce site at this moment.\n \nI built a custom post type in order for products to be added to the site, and have also written some logic so that particular seasons only show up in particular date ranges, for example, Valentine's products will only show up on the lead up to Valentine's.",
        screenshot: "./assets/images/screenshots/ror-screenshot.webp",
        repo: "",
        repoTitle: "",
        deployed: "https://raindropsonroses.co.uk",
        deployedTitle: "Raindrops on Roses Florist",
    },
    {
        title: "Travel List",
        role: "Frontend Developer",
        technologies: [
            {name: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp"},
            {name: "CSS", iconUrl: "./assets/images/icons/frontend/css3.webp"},
            {name: "JavaScript", iconUrl: "./assets/images/icons/frontend/javascript.webp"},
            {name: "BootStrap", iconUrl: "./assets/images/icons/frontend/bootstrap.webp"},
            {name: "jQuery", iconUrl: "./assets/images/icons/frontend/jquery.webp"},
        ],
        description: "This was a team project where I contributed mostly to the implementation of the design given to me. I made the design come to life, customising Bootstrap elements to give them our own colour scheme and look. The Travel List uses Google Maps API and Unsplash API to give users an interactive list that can help them choose where to go on holiday. \n \nTheir favourite places can be stored in a list so they can easily access them again later. The user is shown some images and a map of the destination they have entered. If they do not know where they want to travel they can click the Random button to randomly choose a destination.",
        screenshot: "./assets/images/screenshots/travel-list-screenshot.webp",
        repo: "https://github.com/h-fikri/Travel-List-Jan2023",
        repoTitle: "Travel List 2023",
        deployed: "https://h-fikri.github.io/Travel-List-Jan2023",
        deployedTitle: "Travel List",
    },
    {
        title: "Weather Dashboard",
        role: "Sole Developer",
        technologies: [
            {name: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp"},
            {name: "CSS", iconUrl: "./assets/images/icons/frontend/css3.webp"},
            {name: "JavaScript", iconUrl: "./assets/images/icons/frontend/javascript.webp"},
            {name: "BootStrap", iconUrl: "./assets/images/icons/frontend/bootstrap.webp"},
            {name: "jQuery", iconUrl: "./assets/images/icons/frontend/jquery.webp"},
        ],
        description: "A dashboard that accesses the OpenWeather API to display the current weather for the next five days. After each search a button is created in history to show the last ten places looked at. The user can click on these buttons to easily return back to a place they have already looked at.",
        screenshot: "./assets/images/screenshots/weather-dashboard-screenshot.webp",
        repo: "https://www.github.com/nickmbk/weather-dashboard",
        repoTitle: "Weather Dashboard",
        deployed: "https://nickmbk.github.io/weather-dashboard",
        deployedTitle: "Weather Dashboard",
    },
    {
        title: "Code Quiz",
        role: "Sole Developer",
        technologies: [
            {name: "HTML", iconUrl: "./assets/images/icons/frontend/html5.webp"},
            {name: "CSS", iconUrl: "./assets/images/icons/frontend/css3.webp"},
            {name: "JavaScript", iconUrl: "./assets/images/icons/frontend/javascript.webp"},
        ],
        description: "An interactive quiz about coding. 10 questions, 75 seconds. Every answer you get wrong takes 10 seconds off the timer.\n \nOnce you have answered all questions you score gets saved to the Highscores board. Compete against your coding friends to see who is the best!",
        screenshot: "./assets/images/screenshots/code-quiz-screenshot.webp",
        repo: "https://www.github.com/nickmbk/code-quiz",
        repoTitle: "Code Quiz",
        deployed: "https://nickmbk.github.io/code-quiz",
        deployedTitle: "Code Quiz",
    },
]